#!/bin/sh
set -e

export PYTHONPATH='src/'

export CORPUS="tmp/page_links_nl.mm"
export DICTIONARY="tmp/page_links_nl.dict"
export LSI="tmp/page_links_nl.lsi"
export INDEX="tmp/page_links_nl.index"

cd "$(dirname $0)/.."

if [ -z "$1" ]; then
  echo "Usage: $0 \"identifier\""
  exit 1
fi

python -m link.topic_model.console "$1"
