#!/bin/sh
set -e

export PYTHONPATH='src/'
export PYRO_SERIALIZERS_ACCEPTED=pickle
export PYRO_SERIALIZER=pickle
export PYRO_LOGLEVEL=DEBUG
export PYRO_LOGFILE={stderr}

PAGE_LINKS_URL="http://downloads.dbpedia.org/2016-10/core-i18n/nl/page_links_nl.ttl.bz2"
PAGE_LINKS="tmp/page_links_nl.ttl"

CORPUS="tmp/page_links_nl.mm"
DICTIONARY="tmp/page_links_nl.dict"
LSI="tmp/page_links_nl.lsi"
INDEX="tmp/page_links_nl.index"

cd "$(dirname $0)/.."

if [ ! -e "$PAGE_LINKS" ]; then
  curl "$PAGE_LINKS_URL" | bunzip2 > "$PAGE_LINKS"
fi

if [ ! -e "$CORPUS" ]; then
  echo "Creating $CORPUS..."
  python -m link.topic_model.create_corpus "$PAGE_LINKS" "$CORPUS" "$DICTIONARY"
fi

if [ ! -e "$LSI" ]; then
  echo "Creating $LSI..."
  python -m link.topic_model.create_model "$CORPUS" "$DICTIONARY" "$LSI" "$INDEX"
fi
